import fs from 'node:fs';
import path from 'node:path';
import type { WorkmateDshModelRoute } from './model-route.js';
import { WORKMATE_DSH_API_KEY_ENV, WORKMATE_DSH_PROVIDER_ROUTE } from './model-route.js';

function yamlString(value: string): string {
  // Prefer JSON encoding so special chars / unicode stay valid YAML scalars.
  return JSON.stringify(value);
}

/**
 * Build a jsonrpc-agent-compatible cordis.yml that uses llm-pi-ai with one
 * Workmate-declared provider route (instead of dsh-llm-deepseek only).
 */
export function buildWorkmateDshCordisYaml(route: WorkmateDshModelRoute): string {
  const lines = [
    '# Generated by Workmate — do not edit by hand.',
    '# stdout is reserved for JSON-RPC; no console logger / terminal UI.',
    '',
    '- id: sdk-jsonrpc-server',
    "  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'",
    '  config:',
    '    maxTokensAsSuccess: true',
    '',
    '- id: llm-pi-ai',
    "  name: '@deepseek-ai/dsh-llm-pi-ai'",
    '  config:',
    '    providers:',
    `      ${WORKMATE_DSH_PROVIDER_ROUTE}:`,
    `        displayName: ${yamlString(route.displayName)}`,
    `        apiKeyEnv: ${WORKMATE_DSH_API_KEY_ENV}`,
    `        api: ${route.api}`,
    `        baseURL: ${yamlString(route.baseUrl)}`,
    '        models:',
    `          - id: ${yamlString(route.model)}`,
    `            contextWindow: ${route.contextWindow}`,
    `            maxTokens: ${route.maxTokens}`,
    '',
    '- id: subprocess',
    "  name: '@deepseek-ai/dsh-subprocess-local'",
    '',
    '- id: bash',
    "  name: '@deepseek-ai/dsh-bash-local'",
    '  config:',
    '    cwd: !!js process.env.DSH_CWD ?? process.cwd()',
    '    timeoutMs: 60000',
    '',
    '- id: agent-spine',
    "  name: '@deepseek-ai/dsh-agent-spine-demo'",
    '  config:',
    "    persona: !!js process.env.DSH_SYSTEM_PROMPT ?? 'You are a coding agent.'",
    '    workspaceContext: false',
    '    skills:',
    '      enabled: false',
    '    toolBash:',
    '      enableRunInBackground: false',
    '    toolJobs: false',
    '',
    '- id: sessions',
    "  name: '@deepseek-ai/dsh-session-persistence-jsonl'",
    '  config:',
    "    root: !!js process.env.DSH_SESSION_ROOT ?? './.sessions'",
    "    compression: !!js \"process.env.DSH_SNAPSHOT === undefined ? 'zstd' : 'none'\"",
    '',
    '- id: session-checkpoints',
    "  name: '@deepseek-ai/dsh-session-checkpoint-policy'",
    '',
    '- id: subagent',
    "  name: '@deepseek-ai/dsh-subagent'",
    '',
    '- id: subagent-spawn-in-process',
    "  name: '@deepseek-ai/dsh-subagent-spawn-in-process'",
    '  config:',
    '    providerName: spawn',
    '',
    '- id: tool-subagent',
    "  name: '@deepseek-ai/dsh-tool-subagent'",
    '  config:',
    '    provider: spawn',
    '    toolName: subagent',
    '    enableRunInBackground: false',
    '',
    '- id: tool-todo',
    "  name: '@deepseek-ai/dsh-tool-todo'",
    '  config:',
    '    allowParallelInProgress: true',
    '',
    '- id: fs-local',
    "  name: '@deepseek-ai/dsh-fs-local'",
    '  config:',
    '    cwd: !!js process.env.DSH_CWD ?? process.cwd()',
    '',
    '- id: fs-observation-policy',
    "  name: '@deepseek-ai/dsh-fs-observation-policy'",
    '',
    '- id: tool-fs',
    "  name: '@deepseek-ai/dsh-tool-fs'",
    '',
    '- id: token-meter',
    "  name: '@deepseek-ai/dsh-token-meter'",
    '',
    '- id: compaction-basic',
    "  name: '@deepseek-ai/dsh-compaction-basic'",
    '  config:',
    '    thresholdRatio: 0.8',
    '    retainRatio: 0.16',
    '    maxTokens: 8192',
    '    compactionRetries: 1',
    '',
  ];
  return lines.join('\n');
}

/** Write cordis next to the run workspace; return absolute path. */
export function writeWorkmateDshCordis(workspaceDir: string, route: WorkmateDshModelRoute): string {
  const file = path.join(workspaceDir, '.workmate-dsh.cordis.yml');
  fs.mkdirSync(workspaceDir, { recursive: true });
  fs.writeFileSync(file, buildWorkmateDshCordisYaml(route), 'utf8');
  return file;
}
