<script setup lang="ts">
import { computed, ref } from 'vue';
import type { SkillRecord } from '../../app/capabilities';

const props = defineProps<{ skills: SkillRecord[] }>();
const emit = defineEmits<{ create: [name: string, description: string]; open: [skill: SkillRecord]; remove: [skill: SkillRecord] }>();
const creating = ref(false); const name = ref(''); const description = ref(''); const query = ref('');
const filtered = computed(() => props.skills.filter((skill) => `${skill.name} ${skill.description}`.toLowerCase().includes(query.value.toLowerCase())));
function begin() { creating.value = true; }
function create() { if (!name.value.trim() || !description.value.trim()) return; emit('create', name.value.trim(), description.value.trim()); name.value = ''; description.value = ''; creating.value = false; }
</script>
<template>
  <section class="mx-auto max-w-5xl"><header class="mb-7 flex items-end justify-between gap-5"><div><p class="text-[11px] font-extrabold tracking-[.12em] text-[var(--accent)]">SKILL AUTHORING</p><h2 class="mt-2 text-2xl font-bold tracking-[-.03em]">智能创建与修改</h2><p class="mt-2 text-sm text-[var(--muted)]">每个 Skill 是一个受管目录；从意图出发，在工作区中与系统管理员协作完成。</p></div><button class="shrink-0 rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white shadow-sm" @click="begin">＋ 新增 Skill</button></header>
    <form v-if="creating" class="mb-6 rounded-2xl border border-[var(--accent)] bg-[var(--surface)] p-5 shadow-sm" @submit.prevent="create"><div class="flex items-center justify-between"><div><h3 class="font-bold">创建新的 Skill</h3><p class="mt-1 text-xs text-[var(--muted)]">先创建未保存草案，再进入工作区流式生成 SKILL.md。</p></div><button type="button" class="text-sm text-[var(--muted)]" @click="creating = false">取消</button></div><div class="mt-4 grid gap-3 md:grid-cols-[minmax(180px,.7fr)_minmax(0,1.5fr)_auto]"><input v-model="name" class="rounded-xl border border-[var(--border)] bg-[var(--surface-muted)] px-3 py-2.5 text-sm" placeholder="Skill 名称，例如 excel-workbench" autofocus /><input v-model="description" class="rounded-xl border border-[var(--border)] bg-[var(--surface-muted)] px-3 py-2.5 text-sm" placeholder="意图描述，例如：读取、校验和生成 Excel 报表" /><button class="rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40" :disabled="!name.trim() || !description.trim()">进入工作区</button></div></form>
    <div class="mb-3 flex items-center justify-between"><p class="text-sm font-semibold">我的 Skill <span class="ml-1 font-normal text-[var(--muted)]">{{ filtered.length }}</span></p><input v-model="query" class="w-56 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-xs" placeholder="筛选 Skill…" /></div>
    <div class="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><article v-for="skill in filtered" :key="skill.id" class="group flex items-center gap-4 border-b border-[var(--border)] px-5 py-4 last:border-0"><div class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--accent-soft)] text-sm font-extrabold text-[var(--accent)]">{{ skill.name.slice(0, 1).toUpperCase() }}</div><div class="min-w-0 flex-1"><div class="flex items-center gap-2"><h3 class="truncate font-semibold">{{ skill.name }}</h3><span class="rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-[10px] font-bold uppercase text-[var(--muted)]">本地</span></div><p class="mt-1 truncate text-sm text-[var(--muted)]">{{ skill.description }}</p></div><div class="hidden text-right text-xs text-[var(--muted)] lg:block"><p>SKILL.md</p><p class="mt-1">受管工作区</p></div><button class="shrink-0 rounded-lg px-2 py-2 text-sm font-semibold text-rose-600 opacity-0 transition-opacity group-hover:opacity-100" title="删除 Skill" @click="emit('remove', skill)">删除</button><button class="shrink-0 rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold text-[var(--accent)] group-hover:border-[var(--accent)]" @click="emit('open', skill)">打开工作区 →</button></article><div v-if="!filtered.length" class="p-10 text-center text-sm text-[var(--muted)]">尚未创建 Skill。点击右上角开始创建。</div></div>
  </section>
</template>
