<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { applyOntologyGovernance, readOntologyGovernance, suggestOntologyGovernance, undoOntologyGovernance, type KnowledgeBasePayload, type OntologyGovernanceCommand, type OntologyGovernanceIssue, type OntologyGovernancePayload, type OntologyGovernanceSuggestion, type OntologyWorkflowPayload } from '../../services/api';
import { useNotify } from '../../app/notify';
import OntologyGraphView from './OntologyGraphView.vue';

type ModelPayload={provider:string;baseUrl?:string;chatModel:string;embeddingModel?:string;apiKey:string};
const props=defineProps<{knowledgeBase:KnowledgeBasePayload;model?:ModelPayload}>();
const emit=defineEmits<{updated:[workflow:OntologyWorkflowPayload];proceed:[];back:[]}>();
const notify=useNotify(), data=ref<OntologyGovernancePayload|null>(null), busy=ref(false), aiBusy=ref(false), error=ref(''), aiMessage=ref(''), category=ref('all'), selected=ref<OntologyGovernanceIssue|null>(null), suggestions=ref<OntologyGovernanceSuggestion[]>([]), appliedSuggestionIds=ref(new Set<string>()), canonicalName=ref(''), relationTargetId=ref(''), relationPredicate=ref('关联'), nameValidation=ref<'idle'|'checking'|'empty'|'unchanged'|'valid'|'style-warning'>('idle'), relationDirection=ref<'out'|'in'>('out'), ignored=ref(new Set<string>());
const categories=[['all','全部问题'],['duplicate_node','重复实体'],['naming','命名规范'],['isolated_node','孤立实体'],['orphan_edge','无效关系'],['self_loop','自循环'],['duplicate_edge','重复关系']] as const;
const activeIssues=computed(()=>(data.value?.issues||[]).filter(i=>!ignored.value.has(i.id)));
const visibleIssues=computed(()=>(data.value?.issues||[]).filter(i=>!ignored.value.has(i.id)&&(category.value==='all'||i.category===category.value)));
const blockers=computed(()=>(data.value?.issues||[]).filter(i=>i.severity==='blocker'&&!ignored.value.has(i.id)));
const warnings=computed(()=>(data.value?.issues||[]).filter(i=>i.severity==='warning'&&!ignored.value.has(i.id)));
const selectedNode=computed(()=>(data.value?.graph.nodes as any[]|undefined)?.find(node=>node.id===selected.value?.nodeIds[0]));
const relationTargets=computed(()=>(data.value?.graph.nodes as any[]||[]).filter(node=>node.id!==selected.value?.nodeIds[0]));
const compliantName=computed(()=>nameValidation.value==='valid'||nameValidation.value==='style-warning');
let nameValidationTimer:ReturnType<typeof setTimeout>|undefined;
function validateName(){if(nameValidationTimer)clearTimeout(nameValidationTimer);nameValidation.value='checking';nameValidationTimer=setTimeout(()=>{const value=canonicalName.value.trim(),original=String(selectedNode.value?.name||'').trim();if(!value)nameValidation.value='empty';else if(value.localeCompare(original,undefined,{sensitivity:'accent'})===0)nameValidation.value='unchanged';else if(/^[A-Z0-9_\-]+$/.test(value)||/^(indicator|metric|priority|entity|concept)[_\-]/i.test(value))nameValidation.value='style-warning';else nameValidation.value='valid'},350)}
function validateNameNow(){if(nameValidationTimer)clearTimeout(nameValidationTimer);const value=canonicalName.value.trim(),original=String(selectedNode.value?.name||'').trim();if(!value)nameValidation.value='empty';else if(value.localeCompare(original,undefined,{sensitivity:'accent'})===0)nameValidation.value='unchanged';else if(/^[A-Z0-9_\-]+$/.test(value)||/^(indicator|metric|priority|entity|concept)[_\-]/i.test(value))nameValidation.value='style-warning';else nameValidation.value='valid'}
const affectedGraph=computed(()=>{if(!data.value)return undefined;if(!selected.value)return data.value.graph;const ids=new Set(selected.value.nodeIds), edgeIds=new Set(selected.value.edgeIds);for(const edge of data.value.graph.edges as any[])if(edgeIds.has(edge.id)){ids.add(edge.subjectId);ids.add(edge.objectId)}return {...data.value.graph,nodes:(data.value.graph.nodes as any[]).filter(n=>ids.has(n.id)),edges:(data.value.graph.edges as any[]).filter(e=>edgeIds.has(e.id)||ids.has(e.subjectId)&&ids.has(e.objectId))};});
function count(key:string){return key==='all'?activeIssues.value.length:activeIssues.value.filter(i=>i.category===key).length}
function suggestionStatus(suggestion:OntologyGovernanceSuggestion){if(appliedSuggestionIds.value.has(suggestion.issueId))return 'applied';return data.value?.issues.some(issue=>issue.id===suggestion.issueId)?'pending':'resolved'}
async function load(){busy.value=true;error.value='';try{data.value=await readOntologyGovernance(props.knowledgeBase);if(selected.value)selected.value=data.value.issues.find(i=>i.id===selected.value?.id)||null}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
function choose(issue:OntologyGovernanceIssue){selected.value=issue;canonicalName.value='';nameValidation.value='idle';relationTargetId.value='';relationPredicate.value='关联';relationDirection.value='out'}
async function apply(commands:OntologyGovernanceCommand[],source:'manual'|'rule'|'ai'='manual'){if(!commands.length)return false;busy.value=true;try{const result=await applyOntologyGovernance(props.knowledgeBase,commands,source);emit('updated',result.workflow);await load();selected.value=null;notify.pushRaw('success','草稿已更新','操作已记录，可从操作历史撤销。');return true}catch(e){notify.error(e,'notify.saveFailed');return false}finally{busy.value=false}}
async function applyIssue(){if(!selected.value)return;let commands=selected.value.suggestedCommands;if(selected.value.category==='duplicate_node'&&commands[0]?.type==='merge_nodes'&&canonicalName.value.trim())commands=[{...commands[0],canonicalName:canonicalName.value.trim()}];if(selected.value.category==='naming'&&canonicalName.value.trim())commands=[{type:'rename_node',nodeId:selected.value.nodeIds[0]!,name:canonicalName.value.trim(),keepOldAsAlias:true}];await apply(commands,'rule')}
async function applySuggestion(suggestion:OntologyGovernanceSuggestion){if(suggestionStatus(suggestion)!=='pending')return;const ok=await apply(suggestion.commands,'ai');if(ok)appliedSuggestionIds.value=new Set([...appliedSuggestionIds.value,suggestion.issueId])}
async function keepAsTerm(){if(!selected.value)return;await apply([{type:'mark_term',nodeId:selected.value.nodeIds[0]!}],'manual')}
async function deleteIsolated(){if(!selected.value)return;await apply([{type:'delete_node',nodeId:selected.value.nodeIds[0]!}],'manual')}
async function addRelation(){if(!selected.value||!relationTargetId.value||!relationPredicate.value.trim())return;const own=selected.value.nodeIds[0]!,out=relationDirection.value==='out';await apply([{type:'add_edge',edgeId:`manual-edge-${Date.now()}`,subjectId:out?own:relationTargetId.value,predicate:relationPredicate.value.trim(),objectId:out?relationTargetId.value:own}],'manual')}
async function generateAi(){if(!props.model){error.value='请先配置可用的应用模型。';return}aiBusy.value=true;error.value='';aiMessage.value='';try{suggestions.value=(await suggestOntologyGovernance(props.knowledgeBase,props.model,visibleIssues.value.map(i=>i.id))).suggestions;aiMessage.value=suggestions.value.length?`AI 已生成 ${suggestions.value.length} 条可执行建议，请逐条审核。`:'AI 分析已完成，但没有生成可安全执行的建议。请逐项人工处理，或缩小问题分类后重试。'}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{aiBusy.value=false}}
async function undo(){try{const result=await undoOntologyGovernance(props.knowledgeBase);emit('updated',result.workflow);appliedSuggestionIds.value=new Set();await load()}catch(e){notify.error(e,'notify.saveFailed')}}
function ignore(issue:OntologyGovernanceIssue){ignored.value=new Set([...ignored.value,issue.id]);selected.value=null}
watch(()=>props.knowledgeBase.id,load);onMounted(load);onBeforeUnmount(()=>{if(nameValidationTimer)clearTimeout(nameValidationTimer)});
</script>

<template>
  <section class="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]">
    <header class="flex flex-wrap items-start justify-between gap-3 border-b border-[var(--border)] px-5 py-4">
      <div><h3 class="font-semibold">图谱治理中心</h3><p class="mt-1 text-xs text-[var(--muted)]">逐项处理规则扫描和 AI 建议。所有操作只修改草稿，发布前可撤销。</p></div>
      <div class="flex gap-2"><span class="rounded-full bg-rose-50 px-3 py-1.5 text-xs text-rose-700">阻断 {{ blockers.length }}</span><span class="rounded-full bg-amber-50 px-3 py-1.5 text-xs text-amber-700">建议 {{ warnings.length }}</span><button class="rounded-lg border px-3 py-1.5 text-xs" :disabled="busy" @click="load">重新校验</button><button class="rounded-lg bg-indigo-600 px-3 py-1.5 text-xs text-white" :disabled="aiBusy||!activeIssues.length" @click="generateAi">{{ aiBusy?'AI 分析中…':'AI 辅助治理' }}</button></div>
    </header>
    <div v-if="error" class="border-b border-rose-200 bg-rose-50 px-5 py-3 text-xs text-rose-700"><strong>AI 治理未完成</strong><p class="mt-1">{{ error }}</p></div><div v-else-if="aiMessage" class="border-b border-blue-200 bg-blue-50 px-5 py-3 text-xs text-blue-700">{{ aiMessage }}</div>
    <div class="grid min-h-[600px] lg:grid-cols-[210px_minmax(0,1fr)_330px]">
      <aside class="border-r border-[var(--border)] p-3"><p class="px-2 pb-2 text-[11px] font-semibold text-[var(--muted)]">问题分类</p><button v-for="item in categories" :key="item[0]" class="mb-1 flex w-full justify-between rounded-lg px-3 py-2 text-left text-xs" :class="category===item[0]?'bg-[var(--accent)] text-white':'hover:bg-[var(--surface-muted)]'" @click="category=item[0];selected=null"><span>{{ item[1] }}</span><strong>{{ count(item[0]) }}</strong></button><div class="mt-5 border-t pt-3"><button class="w-full rounded-lg border px-3 py-2 text-xs" :disabled="!data?.operations.some(o=>!o.undoneAt)" @click="undo">↶ 撤销最近操作</button><p class="mt-2 text-[10px] leading-relaxed text-[var(--muted)]">已记录 {{ data?.operations.length||0 }} 条操作。发布后操作历史仍保留。</p><div class="mt-2 max-h-36 space-y-1 overflow-auto"><div v-for="operation in data?.operations.slice(0,5)" :key="operation.id" class="rounded bg-[var(--surface-muted)] px-2 py-1.5 text-[10px]"><span>{{ operation.source==='ai'?'AI':operation.source==='rule'?'规则':'人工' }} · {{ operation.commands.length }} 项</span><span v-if="operation.undoneAt" class="ml-1 text-[var(--muted)]">已撤销</span><time class="block text-[var(--muted)]">{{ new Date(operation.createdAt).toLocaleString() }}</time></div></div></div></aside>
      <main class="min-w-0 border-r border-[var(--border)]"><div class="flex items-center justify-between border-b px-4 py-3"><div><strong class="text-sm">{{ selected?'问题局部图':'待处理问题' }}</strong><p class="mt-0.5 text-[10px] text-[var(--muted)]">{{ selected?'仅显示当前问题涉及的实体和关系':'选择问题查看证据、影响范围及修复方案' }}</p></div><button v-if="selected" class="text-xs text-[var(--accent)]" @click="selected=null">返回列表</button></div>
        <OntologyGraphView v-if="selected" :graph="affectedGraph" title="问题局部关系图" compact />
        <div v-else-if="busy" class="py-20 text-center text-sm text-[var(--muted)]">正在扫描图谱问题…</div>
        <div v-else-if="!visibleIssues.length" class="py-20 text-center"><strong class="text-sm">当前分类没有待处理问题</strong><p class="mt-1 text-xs text-[var(--muted)]">可继续检查其他分类或进入发布。</p></div>
        <div v-else class="divide-y divide-[var(--border)]"><button v-for="issue in visibleIssues" :key="issue.id" class="flex w-full items-start gap-3 px-4 py-3 text-left hover:bg-[var(--surface-muted)]/50" @click="choose(issue)"><span :class="['mt-1 h-2.5 w-2.5 shrink-0 rounded-full',issue.severity==='blocker'?'bg-rose-500':'bg-amber-400']"/><span class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ issue.title }}</strong><span class="mt-1 line-clamp-2 block text-xs text-[var(--muted)]">{{ issue.description }}</span></span><span class="text-[10px] text-[var(--muted)]">{{ issue.nodeIds.length }} 实体 · {{ issue.edgeIds.length }} 关系</span></button></div>
      </main>
      <aside class="p-4"><template v-if="selected"><div class="flex justify-between"><span :class="['rounded px-2 py-1 text-[10px] font-semibold',selected.severity==='blocker'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700']">{{ selected.severity==='blocker'?'阻止发布':'建议处理' }}</span><button v-if="selected.severity==='warning'" class="text-xs text-[var(--muted)]" @click="ignore(selected)">本次忽略</button></div><h4 class="mt-3 font-semibold">{{ selected.title }}</h4><p class="mt-2 text-xs leading-relaxed text-[var(--muted)]">{{ selected.description }}</p><div class="mt-4 rounded-xl bg-[var(--surface-muted)] p-3 text-xs"><p><strong>影响范围</strong></p><p class="mt-1 text-[var(--muted)]">{{ selected.nodeIds.length }} 个实体，{{ selected.edgeIds.length }} 条关系</p></div><template v-if="selected.category==='naming'"><label class="mt-4 block text-xs font-semibold">新的业务显示名称<input v-model="canonicalName" class="mt-1 w-full rounded-lg border p-2 font-normal transition" :class="nameValidation==='valid'?'border-emerald-400 ring-2 ring-emerald-100':nameValidation==='unchanged'||nameValidation==='empty'?'border-rose-300':'border-[var(--border)]'" placeholder="请输入规范、易理解的业务名称" @input="validateName" @blur="validateNameNow" @keydown.enter.prevent="validateNameNow"/></label><div class="mt-1 min-h-5 text-[10px]"><span v-if="nameValidation==='checking'" class="text-blue-600">正在检查名称…</span><span v-else-if="nameValidation==='unchanged'" class="text-rose-600">新名称与原名称相同，请输入不同名称。</span><span v-else-if="nameValidation==='empty'" class="text-rose-600">请输入新的业务显示名称。</span><span v-else-if="nameValidation==='style-warning'" class="text-amber-700">名称已改变，可以采用；建议使用更易理解的业务名称，原名称将保留为别名。</span><span v-else-if="nameValidation==='valid'" class="text-emerald-700">✓ 名称可用，原名称将自动保留为别名。</span></div><div class="mt-4 flex gap-2"><button class="flex-1 rounded-lg border px-3 py-2 text-xs" @click="ignore(selected)">保持现状</button><button class="flex-1 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs text-white disabled:opacity-40" :disabled="!compliantName" @click="applyIssue">采用合规命名</button></div></template>
        <template v-else-if="selected.category==='isolated_node'"><div class="mt-4 space-y-3"><button class="w-full rounded-lg border border-emerald-300 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700" @click="keepAsTerm">保留为术语</button><div class="rounded-xl border border-[var(--border)] p-3"><strong class="text-xs">补充关系</strong><select v-model="relationTargetId" class="mt-2 w-full rounded-lg border border-[var(--border)] p-2 text-xs"><option value="">选择关联实体</option><option v-for="node in relationTargets" :key="node.id" :value="node.id">{{ node.name }} · {{ node.type }}</option></select><div class="mt-2 grid grid-cols-[90px_1fr] gap-2"><select v-model="relationDirection" class="rounded-lg border border-[var(--border)] p-2 text-xs"><option value="out">本实体 →</option><option value="in">→ 本实体</option></select><input v-model="relationPredicate" class="rounded-lg border border-[var(--border)] p-2 text-xs" placeholder="关系名称，如：属于"/></div><button class="mt-2 w-full rounded-lg bg-[var(--accent)] px-3 py-2 text-xs text-white disabled:opacity-40" :disabled="!relationTargetId||!relationPredicate.trim()" @click="addRelation">创建关系并解决孤立问题</button></div><button class="w-full rounded-lg border border-rose-300 px-3 py-2 text-xs text-rose-600" @click="deleteIsolated">从草稿删除实体</button></div></template>
        <template v-else><label v-if="selected.category==='duplicate_node'" class="mt-4 block text-xs font-semibold">合并后的标准名称<input v-model="canonicalName" class="mt-1 w-full rounded-lg border border-[var(--border)] p-2 font-normal" placeholder="输入合并后的标准名称"/></label><div class="mt-4 flex gap-2"><button v-if="selected.severity==='warning'" class="flex-1 rounded-lg border px-3 py-2 text-xs" @click="ignore(selected)">保持现状</button><button class="flex-1 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs text-white disabled:opacity-40" :disabled="!selected.suggestedCommands.length || selected.category==='duplicate_node'&&!canonicalName.trim()" @click="applyIssue">{{ selected.category==='duplicate_node'?'合并到草稿':'应用建议' }}</button></div></template></template><template v-else><h4 class="text-sm font-semibold">治理说明</h4><p class="mt-2 text-xs leading-relaxed text-[var(--muted)]">规则引擎负责确定性检查；AI 只生成结构化修复建议。选择左侧问题后可核对影响并应用到草稿。</p><div v-if="suggestions.length" class="mt-5"><div class="flex justify-between"><strong class="text-xs">AI 建议包</strong><span class="text-[10px] text-[var(--muted)]">{{ suggestions.length }} 条</span></div><article v-for="suggestion in suggestions" :key="suggestion.issueId" :class="['mt-2 rounded-xl border p-3 transition',suggestionStatus(suggestion)==='applied'?'border-emerald-300 bg-emerald-50':suggestionStatus(suggestion)==='resolved'?'border-slate-200 bg-slate-50 opacity-70':'border-[var(--border)] bg-[var(--surface)]']"><div class="flex justify-between gap-2 text-xs"><strong :class="suggestionStatus(suggestion)==='applied'?'text-emerald-700':''">{{ suggestionStatus(suggestion)==='applied'?'✓ 已按建议执行':suggestionStatus(suggestion)==='resolved'?'✓ 问题已由其他操作解决':`${Math.round(suggestion.confidence*100)}% 置信度` }}</strong><button v-if="suggestionStatus(suggestion)==='pending'" class="font-semibold text-[var(--accent)]" @click="applySuggestion(suggestion)">接受</button><span v-else class="shrink-0 text-[10px]" :class="suggestionStatus(suggestion)==='applied'?'text-emerald-700':'text-[var(--muted)]'">{{ suggestionStatus(suggestion)==='applied'?'已执行':'无需再处理' }}</span></div><p class="mt-2 text-[11px] leading-relaxed text-[var(--muted)]">{{ suggestion.reason }}</p></article></div></template></aside>
    </div>
    <footer class="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] px-5 py-4"><p class="text-xs text-[var(--muted)]">{{ blockers.length?`仍有 ${blockers.length} 个阻断问题，处理后才能发布。`:`没有阻断问题；${warnings.length} 个建议问题可处理或保留。` }}</p><div class="flex gap-2"><button class="rounded-lg border px-4 py-2 text-sm" @click="emit('back')">返回候选整理</button><button class="rounded-lg bg-[var(--accent)] px-4 py-2 text-sm text-white disabled:opacity-40" :disabled="!!blockers.length" @click="emit('proceed')">进入发布</button></div></footer>
  </section>
</template>
